// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supa(ctx) {
  return createClient(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search Nutribatidos catalog products by name/description. Returns active products with price, slug, and stock.",
  inputSchema: {
    query: z.string().describe("Free-text search query in Spanish or English."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supa(ctx).from("products").select("id, name, slug, price, stock, short_description, is_active").eq("is_active", true).or(`name.ilike.%${query}%,short_description.ilike.%${query}%`).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supa2(ctx) {
  return createClient2(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "List my orders",
  description: "List the signed-in user's Nutribatidos orders (most recent first).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supa2(ctx).from("orders").select("id, order_code, status, total, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-order.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supa3(ctx) {
  return createClient3(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_order_default = defineTool3({
  name: "get_my_order",
  title: "Get order details",
  description: "Get details, items, and shipment tracking for one of the signed-in user's orders.",
  inputSchema: {
    order_id: z3.string().uuid().describe("Order UUID from list_my_orders.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const s = supa3(ctx);
    const [{ data: order, error: e1 }, { data: items, error: e2 }, { data: shipment }] = await Promise.all([
      s.from("orders").select("*").eq("id", order_id).maybeSingle(),
      s.from("order_items").select("*").eq("order_id", order_id),
      s.from("order_shipments").select("*").eq("order_id", order_id).maybeSingle()
    ]);
    if (e1 || e2) return { content: [{ type: "text", text: (e1 ?? e2).message }], isError: true };
    if (!order) return { content: [{ type: "text", text: "Order not found" }], isError: true };
    const payload = { order, items: items ?? [], shipment: shipment ?? null };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supa4(ctx) {
  return createClient4(globalThis.Deno.env.get("SUPABASE_URL"), globalThis.Deno.env.get("SUPABASE_PUBLISHABLE_KEY"), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in Nutribatidos user's profile (name, email, phone).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supa4(ctx).from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { profile: data ?? null, email: ctx.getUserEmail() };
    return { content: [{ type: "text", text: JSON.stringify(payload) }], structuredContent: payload };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mphrhcuqzkbbnovmdbpc";
var mcp_default = defineMcp({
  name: "nutribatidos-mcp",
  title: "Nutribatidos",
  version: "0.1.0",
  instructions: "Herramientas de la tienda Nutribatidos: buscar productos del cat\xE1logo y consultar los pedidos, env\xEDos y perfil del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, list_my_orders_default, get_my_order_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
